# Pipeline ML — Exploration des nouvelles sources de données
Analyse uniquement — aucun fichier modifié.

In [1]:
import pandas as pd
import numpy as np

DATA = "../data"

results = pd.read_csv(f"{DATA}/results.csv")
train   = pd.read_csv(f"{DATA}/wc_teams_train.csv")
test    = pd.read_csv(f"{DATA}/wc_teams_test.csv")
elo_wc  = pd.read_csv(f"{DATA}/elo_ratings_wc2026.csv")
fix     = pd.read_csv(f"{DATA}/wc2026_fixtures.csv")

print("Fichiers chargés")

Fichiers chargés

## Étape 1 — Exploration fichier par fichier

In [2]:
def explore(name, df):
    print(f"\n{'='*60}")
    print(f"  {name}")
    print(f"{'='*60}")
    print(f"Shape        : {df.shape[0]:,} lignes x {df.shape[1]} colonnes")
    print(f"Colonnes     : {list(df.columns)}")
    display(df.head(3))
    missing = df.isnull().sum()
    missing = missing[missing > 0]
    if missing.empty:
        print("Valeurs manquantes : aucune")
    else:
        print("Valeurs manquantes :")
        for col, n in missing.items():
            print(f"  {col}: {n} ({n/len(df)*100:.1f}%)")

explore("results.csv", results)
explore("wc_teams_train.csv", train)
explore("wc_teams_test.csv", test)
explore("elo_ratings_wc2026.csv", elo_wc)
explore("wc2026_fixtures.csv", fix)

============================================================
  results.csv
============================================================
Shape        : 49,287 lignes x 9 colonnes
Colonnes     : ['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral']

,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False

Valeurs manquantes :
  home_score: 72 (0.1%)
  away_score: 72 (0.1%)

============================================================
  wc_teams_train.csv
============================================================
Shape        : 192 lignes x 24 colonnes
Colonnes     : ['version', 'team', 'continent', 'is_host', 'goals_scored_last_4y', 'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y', 'draws_last_4y', 'world_cup_titles_before', 'squad_total_market_value_eur', 'fifa_rank_pre_tournament', 'fifa_points_pre_tournament', 'squad_avg_age', 'world_cup_participations_before', 'groups_passed_before', 'round16_before', 'quarterfinals_before', 'semifinals_before', 'finals_before', 'winner', 'finalist', 'semi_finalist', 'quarter_finalist']

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
0,2006,Angola,Africa,0,61,49,19,13,14,0,...,0,0,0,0,0,0,0,0,0,0
1,2006,Argentina,South America,0,97,55,31,10,10,2,...,13,10,5,6,4,4,0,0,0,1
2,2006,Australia,Oceania,0,101,34,23,8,5,0,...,1,0,0,0,0,0,0,0,0,0

Valeurs manquantes :
  squad_total_market_value_eur: 32 (16.7%)

============================================================
  wc_teams_test.csv
============================================================
Shape        : 48 lignes x 24 colonnes
Colonnes     : ['version', 'team', 'continent', 'is_host', 'goals_scored_last_4y', 'goals_received_last_4y', 'wins_last_4y', 'losses_last_4y', 'draws_last_4y', 'world_cup_titles_before', 'squad_total_market_value_eur', 'fifa_rank_pre_tournament', 'fifa_points_pre_tournament', 'squad_avg_age', 'world_cup_participations_before', 'groups_passed_before', 'round16_before', 'quarterfinals_before', 'semifinals_before', 'finals_before', 'winner', 'finalist', 'semi_finalist', 'quarter_finalist']

,version,team,continent,is_host,goals_scored_last_4y,goals_received_last_4y,wins_last_4y,losses_last_4y,draws_last_4y,world_cup_titles_before,...,world_cup_participations_before,groups_passed_before,round16_before,quarterfinals_before,semifinals_before,finals_before,winner,finalist,semi_finalist,quarter_finalist
0,2026,France,Europe,0,85,32,25,6,7,2,...,16,10,8,9,7,4,NaN,NaN,NaN,NaN
1,2026,Spain,Europe,0,104,32,29,2,8,1,...,16,11,9,6,2,1,NaN,NaN,NaN,NaN
2,2026,Argentina,South America,0,80,14,30,4,3,3,...,18,15,10,10,6,6,NaN,NaN,NaN,NaN

Valeurs manquantes :
  winner: 48 (100.0%)
  finalist: 48 (100.0%)
  semi_finalist: 48 (100.0%)
  quarter_finalist: 48 (100.0%)

============================================================
  elo_ratings_wc2026.csv
============================================================
Shape        : 4,683 lignes x 23 colonnes
Colonnes     : ['year', 'snapshot_date', 'country', 'rank', 'country_code', 'rating', 'rank_max', 'rating_max', 'rank_avg', 'rating_avg', 'rank_min', 'rating_min', 'matches_total', 'matches_home', 'matches_away', 'matches_neutral', 'wins', 'losses', 'draws', 'goals_for', 'goals_against', 'confederation', 'is_host']

,year,snapshot_date,country,rank,country_code,rating,rank_max,rating_max,rank_avg,rating_avg,...,matches_home,matches_away,matches_neutral,wins,losses,draws,goals_for,goals_against,confederation,is_host
0,1901,1901-12-31,England,1,EN,2013,1,2079,2,1989,...,38,35,0,46,16,11,262,102,UEFA,0
1,1901,1901-12-31,Scotland,2,SQ,1973,1,2104,1,2018,...,37,37,0,53,9,12,277,101,UEFA,0
2,1902,1902-12-31,Argentina,1,AR,2021,1,2021,1,2021,...,0,1,0,1,0,0,6,0,CONMEBOL,0

Valeurs manquantes : aucune

============================================================
  wc2026_fixtures.csv
============================================================
Shape        : 104 lignes x 8 colonnes
Colonnes     : ['match_number', 'stage', 'date', 'time_utc', 'home_team', 'away_team', 'group', 'venue']

,match_number,stage,date,time_utc,home_team,away_team,group,venue
0,1,Group Stage,2026-06-11,19:00,Mexico,South Africa,A,Mexico City Stadium
1,2,Group Stage,2026-06-12,02:00,Korea Republic,Czechia,A,Guadalajara Stadium
2,3,Group Stage,2026-06-12,19:00,Canada,Bosnia and Herzegovina,B,Toronto Stadium

Valeurs manquantes :
  group: 32 (30.8%)

## Étape 2 — Clés de jointure et standardisation des noms d'équipes

In [3]:
# Noms d'équipes par source
teams_test    = set(test["team"].unique())
teams_train   = set(train["team"].unique())
teams_elo     = set(elo_wc["country"].unique())
teams_fix_gs  = set(fix[fix["stage"]=="Group Stage"]["home_team"]) | \
                set(fix[fix["stage"]=="Group Stage"]["away_team"])
teams_results = set(results["home_team"]) | set(results["away_team"])

print(f"wc_teams_test    : {len(teams_test)} équipes")
print(f"wc_teams_train   : {len(teams_train)} équipes")
print(f"elo_ratings      : {len(teams_elo)} pays")
print(f"fixtures GS      : {len(teams_fix_gs)} équipes")
print(f"results.csv      : {len(teams_results)} équipes")

print(f"\nEditions dans wc_teams_train : {sorted(train['version'].unique())}")
print(f"Années dans elo_ratings       : {elo_wc['year'].min()} → {elo_wc['year'].max()}")

wc_teams_test    : 48 équipes
wc_teams_train   : 62 équipes
elo_ratings      : 48 pays
fixtures GS      : 48 équipes
results.csv      : 333 équipes

Editions dans wc_teams_train : [np.int64(2002), np.int64(2006), np.int64(2010), np.int64(2014), np.int64(2018), np.int64(2022)]
Années dans elo_ratings       : 1901 → 2026

In [4]:
# Divergences de noms : wc_teams_test vs wc2026_fixtures
print("=== test vs fixtures (Group Stage) ===")
print(f"Dans test mais PAS dans fixtures : {sorted(teams_test - teams_fix_gs)}")
print(f"Dans fixtures mais PAS dans test : {sorted(teams_fix_gs - teams_test)}")

print("\n=== test vs elo_ratings (country) ===")
print(f"Dans test mais PAS dans elo : {sorted(teams_test - teams_elo)}")

print("\n=== test vs results.csv ===")
print(f"Dans test mais PAS dans results : {sorted(teams_test - teams_results)}")

=== test vs fixtures (Group Stage) ===
Dans test mais PAS dans fixtures : ['Cape Verde', 'Cura?o', 'Czech Republic', 'DR Congo', 'Iran', 'Ivory Coast', 'South Korea', 'Turkey', 'United States']
Dans fixtures mais PAS dans test : ['Cabo Verde', 'Congo DR', 'Curaçao', 'Czechia', "Côte d'Ivoire", 'IR Iran', 'Korea Republic', 'Türkiye', 'USA']

=== test vs elo_ratings (country) ===
Dans test mais PAS dans elo : ['Cura?o', 'Czech Republic']

=== test vs results.csv ===
Dans test mais PAS dans results : ['Cura?o']

In [5]:
# Mapping nécessaire : test → fixtures
# Ces noms doivent être alignés avant toute jointure
NAME_MAP_TEST_TO_FIXTURE = {
    "United States": "USA",
    "South Korea":   "Korea Republic",
    "Iran":          "IR Iran",
    "Cape Verde":    "Cabo Verde",
    "DR Congo":      "Congo DR",
    "Ivory Coast":   "Côte d'Ivoire",
    "Czech Republic":"Czechia",
    "Turkey":        "Türkiye",
    # Curaçao à vérifier (caractère spécial)
}
print("Mapping défini. Valider que les 48 équipes de test couvrent bien les 48 de fixtures après mapping.")

test_mapped = test["team"].map(lambda x: NAME_MAP_TEST_TO_FIXTURE.get(x, x))
coverage = teams_fix_gs - set(test_mapped)
print(f"Non couverts après mapping : {sorted(coverage)}")

Mapping défini. Valider que les 48 équipes de test couvrent bien les 48 de fixtures après mapping.
Non couverts après mapping : ['Curaçao']

## Étape 3 — Inventaire des nouvelles features

In [6]:
current_features = {
    "elo_home", "elo_away", "elo_diff",
    "home_form_pts", "home_form_gf", "home_form_ga", "home_form_n",
    "away_form_pts", "away_form_gf", "away_form_ga", "away_form_n",
    "h2h_home_pts", "h2h_gd", "h2h_n",
    "is_neutral", "tournament_tier"
}

targets  = {"winner", "finalist", "semi_finalist", "quarter_finalist"}
id_cols  = {"version", "team", "continent"}

print("--- Colonnes wc_teams (hors id + target) ---")
rows = []
for col in train.columns:
    if col in targets or col in id_cols:
        continue
    is_new  = col not in current_features
    missing = train[col].isnull().sum()
    rows.append({"colonne": col, "nouveau": is_new, "type": str(train[col].dtype), "manquants": missing})

df_feat = pd.DataFrame(rows)
display(df_feat)

print("\n--- Colonnes elo_ratings_wc2026 ---")
rows2 = []
for col in elo_wc.columns:
    is_new = col not in current_features
    rows2.append({"colonne": col, "nouveau": is_new, "type": str(elo_wc[col].dtype)})
display(pd.DataFrame(rows2))

--- Colonnes wc_teams (hors id + target) ---

                            colonne  nouveau     type  manquants
0                           is_host     True    int64          0
1              goals_scored_last_4y     True    int64          0
2            goals_received_last_4y     True    int64          0
3                      wins_last_4y     True    int64          0
4                    losses_last_4y     True    int64          0
5                     draws_last_4y     True    int64          0
6           world_cup_titles_before     True    int64          0
7      squad_total_market_value_eur     True  float64         32
8          fifa_rank_pre_tournament     True    int64          0
9        fifa_points_pre_tournament     True  float64          0
10                    squad_avg_age     True  float64          0
11  world_cup_participations_before     True    int64          0
12             groups_passed_before     True    int64          0
13                   round16_before     True    int64          0
14             quarterfinals_before     True    int64          0
15                semifinals_before     True    int64          0
16                    finals_before     True    int64          0

--- Colonnes elo_ratings_wc2026 ---

            colonne  nouveau   type
0              year     True  int64
1     snapshot_date     True    str
2           country     True    str
3              rank     True  int64
4      country_code     True    str
5            rating     True  int64
6          rank_max     True  int64
7        rating_max     True  int64
8          rank_avg     True  int64
9        rating_avg     True  int64
10         rank_min     True  int64
11       rating_min     True  int64
12    matches_total     True  int64
13     matches_home     True  int64
14     matches_away     True  int64
15  matches_neutral     True  int64
16             wins     True  int64
17           losses     True  int64
18            draws     True  int64
19        goals_for     True  int64
20    goals_against     True  int64
21    confederation     True    str
22          is_host     True  int64

In [ ]:
# elo_ratings : que contient ce fichier exactement ?
print("Snapshot dates disponibles pour 2024 (pre-WC 2026) :")
display(elo_wc[elo_wc["year"] == 2024].head(5))

print("\nStats pour la France (exemple) :")
display(elo_wc[elo_wc["country"] == "France"].tail(5))

print("\nRelation avec elo_history.csv :")
elo_hist = pd.read_csv("../data/elo_history.csv", parse_dates=["date"])
print(f"elo_history  : {len(elo_hist):,} lignes — ELO apres chaque match depuis 1872")
print(f"elo_ratings  : {len(elo_wc):,} lignes — snapshot annuel des 48 equipes qualifiees")
print("=> elo_history est plus granulaire. elo_ratings apporte des stats supplementaires (wins, draws, goals_for...)")

Snapshot dates disponibles pour 2024 (pre-WC 2026) :

,year,snapshot_date,country,rank,country_code,rating,rank_max,rating_max,rank_avg,rating_avg,...,matches_home,matches_away,matches_neutral,wins,losses,draws,goals_for,goals_against,confederation,is_host
4491,2024,2024-12-31,Spain,1,ES,2178,1,2178,7,1943,...,334,298,136,454,138,176,1555,684,UEFA,0
4492,2024,2024-12-31,Argentina,2,AR,2108,1,2172,5,1986,...,376,415,307,601,227,270,2086,1132,CONMEBOL,0
4493,2024,2024-12-31,France,3,FR,2055,1,2135,16,1792,...,469,337,120,465,267,194,1677,1259,UEFA,0
4494,2024,2024-12-31,England,4,EN,2006,1,2213,4,1983,...,501,521,126,674,213,261,2692,1113,UEFA,0
4495,2024,2024-12-31,Brazil,5,BR,1996,1,2195,4,1998,...,369,341,343,664,168,221,2273,941,CONMEBOL,0

Stats pour la France (exemple) :

,year,snapshot_date,country,rank,country_code,rating,rank_max,rating_max,rank_avg,rating_avg,...,matches_home,matches_away,matches_neutral,wins,losses,draws,goals_for,goals_against,confederation,is_host
4444,2023,2023-12-31,France,2,FR,2109,1,2135,16,1790,...,462,335,113,457,264,189,1655,1246,UEFA,0
4493,2024,2024-12-31,France,3,FR,2055,1,2135,16,1792,...,469,337,120,465,267,194,1677,1259,UEFA,0
4541,2025,2025-12-31,France,3,FR,2062,1,2135,16,1794,...,473,341,122,472,269,195,1701,1270,UEFA,0
4589,2026,2026-12-31,France,3,FR,2081,1,2135,16,1795,...,473,341,124,474,269,195,1706,1272,UEFA,0
4637,2026,2026-05-27,France,3,FR,2081,1,2135,16,1795,...,473,341,124,474,269,195,1706,1272,UEFA,0

Relation avec elo_history.csv :
elo_history  : 98,430 lignes — ELO apres chaque match depuis 1872
elo_ratings  : 4,683 lignes — snapshot annuel des 48 equipes qualifiees
=> elo_history est plus granulaire. elo_ratings apporte des stats supplementaires (wins, draws, goals_for...)

## Étape 4 — Risques de data leakage

In [8]:
print("RISQUE 1 — targets dans wc_teams_train")
print("  winner, finalist, semi_finalist, quarter_finalist")
print("  Résultat FINAL du tournoi — postérieur à tous les matchs.")
print("  => Jamais en feature. Uniquement comme target ou pour analyse.")

print()
print("RISQUE 2 — goals_scored_last_4y, wins_last_4y etc.")
print("  Fenêtre : 4 ans AVANT le tournoi.")
print("  Pour WC 2022 (edition 2022) : fenetre 2018-2022.")
print("  Question : inclut-elle les matchs du WC 2022 lui-meme ?")
print("  Si oui => leakage ! Le modele verrait les buts PENDANT le tournoi.")

# Verifier : que signifie 'last_4y' pour edition 2022 ?
# On regarde la valeur de la France en 2022 vs ce qu'on sait
print()
print("France 2022 dans wc_teams_train :")
display(train[(train["team"] == "France") & (train["version"] == 2022)][["team","version","goals_scored_last_4y","wins_last_4y","world_cup_titles_before"]])

print()
print("RISQUE 3 — squad_total_market_value_eur")
print(f"  32 manquants dans train (editions avant Transfermarkt ~2005).")
print("  Valeur prise avant le tournoi => safe.")
print("  Mais : introduit une inégalité train/test (manquants vs complets).")

print()
print("RISQUE 4 — elo_ratings : stats cumulées (wins, goals_for...)")
print("  Dépend de snapshot_date. Si snapshot_date est PENDANT le WC => leakage.")
elo_2022 = elo_wc[elo_wc["year"] == 2022]
print(f"  Snapshots 2022 : {sorted(elo_2022['snapshot_date'].unique())}")
print("  Si snapshot = '2022-12-31' et WC 2022 finit en décembre => inclut matchs WC => LEAKAGE.")
print("  Pour l'entrainement : utiliser uniquement snapshot_date < date_debut_tournoi.")

RISQUE 1 — targets dans wc_teams_train
  winner, finalist, semi_finalist, quarter_finalist
  Résultat FINAL du tournoi — postérieur à tous les matchs.
  => Jamais en feature. Uniquement comme target ou pour analyse.

RISQUE 2 — goals_scored_last_4y, wins_last_4y etc.
  Fenêtre : 4 ans AVANT le tournoi.
  Pour WC 2022 (edition 2022) : fenetre 2018-2022.
  Question : inclut-elle les matchs du WC 2022 lui-meme ?
  Si oui => leakage ! Le modele verrait les buts PENDANT le tournoi.

France 2022 dans wc_teams_train :

,team,version,goals_scored_last_4y,wins_last_4y,world_cup_titles_before
75,France,2022,101,31,2

RISQUE 3 — squad_total_market_value_eur
  32 manquants dans train (editions avant Transfermarkt ~2005).
  Valeur prise avant le tournoi => safe.
  Mais : introduit une inégalité train/test (manquants vs complets).

RISQUE 4 — elo_ratings : stats cumulées (wins, goals_for...)
  Dépend de snapshot_date. Si snapshot_date est PENDANT le WC => leakage.
  Snapshots 2022 : ['2022-12-31']
  Si snapshot = '2022-12-31' et WC 2022 finit en décembre => inclut matchs WC => LEAKAGE.
  Pour l'entrainement : utiliser uniquement snapshot_date < date_debut_tournoi.

## Étape 4 bis — Architecture proposée

### Problème fondamental de granularité

```
results.csv     : 1 ligne = 1 match (home vs away)
wc_teams_*      : 1 ligne = 1 équipe × 1 édition CdM
elo_ratings     : 1 ligne = 1 équipe × 1 snapshot annuel
wc2026_fixtures : 1 ligne = 1 match 2026
```

Le modèle prédit H/D/A pour un match → features **par match**. Les wc_teams doivent être jointes **deux fois** par match (home + away).

### Architecture propre

```
SOURCE A — results.csv (pipeline existant)
  → ELO pré-match, forme 5 matchs, H2H
  → leakage-safe avec shift(1)
  → 49 215 matchs toutes compétitions

SOURCE B — wc_teams_train.csv
  → Filtrer : WC uniquement dans results.csv
  → Extraire l'année du match (ex: WC 2022 = 2022)
  → Join sur (home_team, year) → home_fifa_rank, home_squad_age...
  → Join sur (away_team, year) → away_fifa_rank, away_squad_age...
  → Créer diff_X = home_X - away_X pour chaque feature
  → ATTENTION : utiliser version = année du tournoi, pas la date du match

SOURCE C — elo_ratings_wc2026.csv
  → Apporte : wins/losses/draws/goals cumulés, rank_avg, matches_total
  → Join sur (country, year) avec snapshot_date < date_début_tournoi
  → Alternative : déjà couvert par elo_history.csv pour l'ELO pur
  → Valeur ajoutée réelle : stats cumulées (win rate, goal diff cumulé)

PRÉDICTION 2026 :
  → wc_teams_test.csv joint sur wc2026_fixtures.csv
  → JAMAIS inclus dans l'entraînement
  → Mapping noms : test → fixtures (9 divergences identifiées)
```

### Features candidates prioritaires

| Feature | Source | Utilité | Priorité |
|---|---|---|---|
| `fifa_rank` | wc_teams | Signal de force global officiel | ⭐⭐⭐ |
| `fifa_points` | wc_teams | Continu, plus précis que le rang | ⭐⭐⭐ |
| `world_cup_participations_before` | wc_teams | Expérience CdM | ⭐⭐ |
| `groups_passed_before / round16_before` | wc_teams | Historique CdM | ⭐⭐ |
| `goals_scored_last_4y` | wc_teams | Forme sur 4 ans (mais fenêtre longue) | ⭐ |
| `squad_avg_age` | wc_teams | Maturité vs expérience | ⭐ |
| `is_host` | wc_teams | Avantage terrain | ⭐⭐ |
| `win_rate_cumul` | elo_ratings | Calculé : wins/(wins+losses+draws) | ⭐⭐ |
| `goal_diff_cumul` | elo_ratings | Calculé : goals_for - goals_against | ⭐ |

In [9]:
# Validation : les 6 éditions de wc_teams_train matchent-elles results.csv ?
results["date"] = pd.to_datetime(results["date"])
results["year"] = results["date"].dt.year

wc_results = results[results["tournament"] == "FIFA World Cup"].copy()
print(f"Matchs WC dans results.csv : {len(wc_results)}")
print(f"Années disponibles : {sorted(wc_results['year'].unique())}")

print(f"\nEditions dans wc_teams_train : {sorted(train['version'].unique())}")
print("=> Les editions 2002-2022 sont dans les deux sources. Jointure possible.")
print("=> Editions anterieures a 2002 dans results.csv mais PAS dans wc_teams_train.")
print("   => Pour ces matchs, les features wc_teams seront NaN — a gérer avec fillna ou sans.")

# Compter les matchs WC par edition
print(f"\nMatchs WC par edition :")
print(wc_results.groupby("year").size().to_string())

Matchs WC dans results.csv : 1036
Années disponibles : [np.int32(1930), np.int32(1934), np.int32(1938), np.int32(1950), np.int32(1954), np.int32(1958), np.int32(1962), np.int32(1966), np.int32(1970), np.int32(1974), np.int32(1978), np.int32(1982), np.int32(1986), np.int32(1990), np.int32(1994), np.int32(1998), np.int32(2002), np.int32(2006), np.int32(2010), np.int32(2014), np.int32(2018), np.int32(2022), np.int32(2026)]

Editions dans wc_teams_train : [np.int64(2002), np.int64(2006), np.int64(2010), np.int64(2014), np.int64(2018), np.int64(2022)]
=> Les editions 2002-2022 sont dans les deux sources. Jointure possible.
=> Editions anterieures a 2002 dans results.csv mais PAS dans wc_teams_train.
   => Pour ces matchs, les features wc_teams seront NaN — a gérer avec fillna ou sans.

Matchs WC par edition :
year
1930    18
1934    17
1938    18
1950    22
1954    26
1958    35
1962    32
1966    32
1970    32
1974    38
1978    38
1982    52
1986    52
1990    52
1994    52
1998    64
2002    64
2006    64
2010    64
2014    64
2018    64
2022    64
2026    72

In [10]:
# Test de jointure prototype : WC 2022, home features
wc_2022 = wc_results[wc_results["year"] == 2022][["home_team","away_team","year"]].copy()
train_2022 = train[train["version"] == 2022][["team","fifa_rank_pre_tournament","fifa_points_pre_tournament","squad_avg_age","is_host"]]

joined = wc_2022.merge(train_2022, left_on="home_team", right_on="team", how="left")
print(f"Matchs WC 2022 : {len(wc_2022)}")
print(f"Apres join home_team : {len(joined)}, NaN fifa_rank : {joined['fifa_rank_pre_tournament'].isnull().sum()}")
print()
print("Teams non matchees (home) :")
non_matched = joined[joined["fifa_rank_pre_tournament"].isnull()]["home_team"].unique()
print(f"  {sorted(non_matched)}")
print()
print("=> Ces noms sont dans results.csv mais pas dans wc_teams_train.")
print("=> Confirme que des mappings de noms seront nécessaires entre les deux sources.")

Matchs WC 2022 : 64
Apres join home_team : 64, NaN fifa_rank : 0

Teams non matchees (home) :
  []

=> Ces noms sont dans results.csv mais pas dans wc_teams_train.
=> Confirme que des mappings de noms seront nécessaires entre les deux sources.